development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: myapp
  password: password1

production:
    adapter: postgresql
    encoding: unicode
    database: job_board_production
    pool: 5
